Redis cluster redis classes
splitio/dotnet-client pull request #243
Opened 2024-10-01 20:10 UTC by chillaq

# .NET SDK

## What did you accomplish?

## How do we test the changes introduced in this PR?

## Extra Notes

2024-10-02 15:07 UTC, sanzmauro requested changes
Added some suggestions. Also, are you working to adding config validations in upcoming PRs? or should we add in this one?

2024-10-02 15:07 UTC, sanzmauro commented on Splitio.Redis/Services/Cache/Classes/BaseAdapter.cs
> +        }
```suggestion
        }

        protected List<IServer> GetServers()
        {
            var conn = _pool.GetConnection();
            var servers = new List<IServer>();
            var endpoints = conn?.GetEndPoints();
        
            foreach (var endpoint in endpoints)
            {
                servers.Add(conn.GetServer(endpoint));
            }
        
            return servers;
        }
```

2024-10-02 15:07 UTC, sanzmauro commented on Splitio.Redis/Services/Cache/Classes/BaseAdapter.cs
>              return conn?.GetServer(_config.HostAndPort);
if we are adding `GetServers()`, I suggest to remove `GetServer()`

2024-10-02 15:07 UTC, sanzmauro commented on Splitio.Redis/Services/Cache/Classes/ConnectionPoolManager.cs
> +            }
```suggestion
            };

            if (redisCfg.ClusterNodes != null)
            {
                foreach (var host in redisCfg.ClusterNodes.EndPoints)
                {
                    config.EndPoints.Add(host);
                }
            }
            else
            {
                config.EndPoints.Add(redisCfg.HostAndPort);
            }
```

2024-10-02 15:07 UTC, sanzmauro commented on Splitio.Redis/Services/Domain/RedisConfig.cs
> +        public bool ClusterMode { get; set; }
```suggestion
        public ClusterNodes ClusterNodes { get; set; }
```

2024-10-02 15:07 UTC, sanzmauro commented on Splitio.Redis/Services/Domain/RedisConfig.cs
> +            ClusterMode = ClusterNodes != null;
```suggestion
    ClusterNodes = options.RedisClusterNodes;
```

2024-10-02 15:07 UTC, sanzmauro commented on tests/Splitio-tests/Integration Tests/Impressions/RedisImpressionsCacheTests.cs
> +
empty line

2024-10-02 15:07 UTC, sanzmauro commented on tests/Splitio-tests/Integration Tests/RedisClientTests.cs
> +                API_KEY);
```suggestion
            var client2 = new RedisClient(GetRedisClusterConfigurationOptions(), API_KEY);
```

2024-10-02 15:07 UTC, sanzmauro commented on tests/Splitio-tests/Integration Tests/RedisClientTests.cs
> +                API_KEY);
```suggestion
            var client2 = new RedisClient(GetRedisClusterConfigurationOptions(), API_KEY);
```

2024-10-02 15:07 UTC, sanzmauro commented on tests/Splitio-tests/Integration Tests/RedisClientTests.cs
> +                API_KEY);
same here

2024-10-02 15:07 UTC, sanzmauro commented on tests/Splitio-tests/Integration Tests/RedisClientTests.cs
> +API_KEY);
same here

2024-10-02 15:07 UTC, sanzmauro commented on tests/Splitio.Tests.Common/BaseAsyncClientTests.cs
> +using Splitio.Redis;
why do you need this?

2024-10-02 15:50 UTC, chillaq commented on Splitio.Redis/Services/Cache/Classes/BaseAdapter.cs
>              return conn?.GetServer(_config.HostAndPort);
I will remove it and will update the code that use it in RedisAdapterConsumer

2024-10-02 15:57 UTC, chillaq commented on Splitio.Redis/Services/Domain/RedisConfig.cs
> +            ClusterMode = ClusterNodes != null;
I will need to update all code that uses these properties.

2024-10-02 16:14 UTC, chillaq commented on tests/Splitio-tests/Integration Tests/RedisClientTests.cs
> +                API_KEY);
will do

2024-10-02 16:14 UTC, chillaq commented on tests/Splitio-tests/Integration Tests/RedisClientTests.cs
> +API_KEY);
ok

2024-10-02 16:17 UTC, chillaq commented on tests/Splitio.Tests.Common/BaseAsyncClientTests.cs
> +using Splitio.Redis;
will remove

2024-10-03 16:02 UTC, sanzmauro approved these changes

2024-10-03 16:02 UTC, sanzmauro commented on Splitio.Redis/Services/Domain/RedisConfig.cs
> +    ClusterNodes = options.RedisClusterNodes;
```suggestion
            PoolSize = options.PoolSize ?? 1;
            ClusterNodes = options.RedisClusterNodes;
```

2024-10-03 16:05 UTC, merged